const error = "Algo saliÃ³ mal"

export const miPromesa = Promise.reject(error)

miPromesa
    .catch((error) => {
        console.log("Error de la promesa: ", error)
    })